development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://vmjnbtewtpjvem:db417a0aa00d6137936508f9fedb69ed090739b5dc27454ed03406838ef53e4d@ec2-54-235-242-63.compute-1.amazonaws.com:5432/deu2cb2fes26cd
  channel_prefix: firstapp_production
